name: CI Pipeline

on:
  push:
  pull_request:
    

jobs:
  run-tests:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: taskmaster
          POSTGRES_USER: swen610
          POSTGRES_PASSWORD: whowatchesthewatchmen
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U swen610 -v"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python3 -m pip install -qr requirements.txt
        
    - name: Configure credentials
      run: cp config/gitlab-credentials.yml config/db.yml

    - name: Check Python version
      run: python3 --version

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h postgres -p 5432 -U swen610 -v; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 3
        done

    - name: Start server
      run: python3 src/server.py &  # Running the server in the background

    - name: Wait for the server to be ready
      run: sleep 3

    - name: Run tests
      run: |
        python3 -m coverage run -m unittest -v
        python3 -m coverage report
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
